### ISSUE TITLE
bug: syncer is not updating reported state in downsynced objects

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#477]
### Describe the bug

When the syncer attempts to write to the `status` subobject of a downsynced object, of a kind defined in the APIExport of kubernetes from the `root:compute` workspace, in a mailbox workspace, the write is rejected due to an authorization failure.

### Steps To Reproduce

See above.

### Expected Behaviour

For downsynced objects of all kinds, reported state should propagate from the managed cluster to the mailbox workspace.

### Additional Context

This can be fixed by adding RBAC objects to `root:compute`.  @yana1205 , can you please show us exactly what needs to be added?

**Comment by yana1205** [comment]
Thanks for considering it.

> can you please show us exactly what needs to be added?

Sure. The exact step is as follows:
1. Switch workspace to `root:compute`
    ```
    kubectl ws root:compute
    ```
1. Create the following ClusterRole to extend the existing roles defined in ClusterRole of `compute:apiexport:kubernetes:maximal-permission-policy` to permissions of `update` and `patch` against subresources.
    ```
    kubectl apply -f - << EOF
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: compute:apiexport:kubernetes:maximal-permission-policy-extended
    rules:
    - apiGroups:
      - ""
      resources:
      - services/status
      verbs:
      - update
      - patch
    - apiGroups:
      - apps
      resources:
      - deployments/status
      verbs:
      - update
      - patch
    - apiGroups:
      - apps
      resources:
      - deployments/scale
      verbs:
      - get
      - update
      - patch
    - apiGroups:
      - networking.k8s.io
      resources:
      - ingresses/status
      verbs:
      - update
      - patch
    - apiGroups:
      - ""
      resources:
      - pods/status
      verbs:
      - update
      - patch
    EOF
    ```
1. Create the following ClusterRoleBinding to bind the created ClusterRole with the subjects defined in ClusterRoleBinding of `compute:authenticated:apiexport:kubernetes:maximal-permission-policy`.
    ```
    kubectl apply -f - << EOF
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: compute:authenticated:apiexport:kubernetes:maximal-permission-policy-extended
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: compute:apiexport:kubernetes:maximal-permission-policy-extended
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: apis.kcp.io:binding:system:authenticated
    EOF
    ```

#### How to verify
1. Create a workspace and enter the workspace
    ```
    kubectl ws root
    kubectl ws create ws1 --enter
    ```
1. Create an APIBinding against "kubernetes" APIExport in `root:compute` workspace
    ```
    kubectl apply -f - << EOF
    apiVersion: apis.kcp.io/v1alpha1
    kind: APIBinding
    metadata:
      name: bind-kube
    spec:
      reference:
        export:
          path: "root:compute"
          name: kubernetes
    EOF
    ```
1. Create a sample deployment
    ```
    kubectl apply -f - << EOF
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: busybox
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: busybox
      template:
        metadata:
          labels:
            app: busybox
        spec:
          containers:
          - name: busybox
            image: busybox
            args: ["tail", "-f", "/dev/null"]
          terminationGracePeriodSeconds: 3
    EOF
    ```
1. Check if updating deployment status succeeds
    ```
    kubectl patch deployment busybox --subresource status -p "$(cat << EOF
    status:
      availableReplicas: 1
      conditions:
      - lastTransitionTime: "2023-04-15T03:34:23Z"
        lastUpdateTime: "2023-04-15T03:34:23Z"
        message: Deployment has minimum availability.
        reason: MinimumReplicasAvailable
        status: "True"
        type: Available
      observedGeneration: 1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
    EOF
    )"
    ```

Without the extended ClusterRole, the above patch operation would fail. For example,
1. Delete the ClusterRole (`compute:apiexport:kubernetes:maximal-permission-policy-extended`) in `root:compute`
    ```
    kubectl ws root:compute
    kubectl delete clusterrole compute:apiexport:kubernetes:maximal-permission-policy-extended
    ```
1. Update deployment status
    ```
    $ kubectl ws root:ws1
    $ kubectl patch deployment busybox --subresource status -p "$(cat << EOF
    status:
      availableReplicas: 1
      conditions:
      - lastTransitionTime: "2023-04-15T03:34:23Z"
        lastUpdateTime: "2023-04-15T03:34:23Z"
        message: Deployment has minimum availability.
        reason: MinimumReplicasAvailable
        status: "True"
        type: Available
      observedGeneration: 1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
    EOF
    )"

    Error from server (Forbidden): deployments.apps "busybox" is forbidden: User "kcp-admin" cannot patch resource "deployments/status" in API group "apps" in the namespace "default": access denied
    ```

**Comment by MikeSpreitzer** [comment]
Thanks, @yana1205 .  I see that the ClusterRoleBinding displayed above is very permissive --- it binds the ClusterRole to every authenticated client.  Could we solve the problem with a less permissive ClusterRoleBinding?

**Comment by MikeSpreitzer** [comment]
Also: why is it necessary to add the privilege to GET the /scale subresource of deployments?

**Comment by yana1205** [comment]
Re: Could we solve the problem with a less permissive ClusterRoleBinding?

Yes. It can be done by  creating a less permissive RBAC in the workspaces consuming `root:compute` kubernetes API.
For example, I created a service account and create the Role and RoleBinding in workspace ws1 like this.
```
$ kubectl ws root:ws1
$ kubectl apply -f - << EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments/status"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: test
  namespace: default
EOF
```
This service account is not permitted to update deployment status.
```
$ KUBECONFIG=$workdir/kubeconfig.test.yaml kubectl patch deployment busybox --patch-file $manifests_dir/deployments/patch-status.yaml --subresource status

Error from server (Forbidden): deployments.apps "busybox" is forbidden: User "system:serviceaccount:default:test" cannot patch resource "deployments/status" in API group "apps" in the namespace "default": access denied
```

---


Re: Also: why is it necessary to add the privilege to GET the /scale subresource of deployments?

No. Sorry, I didn't notice that this privilege has already been defined in `compute:apiexport:kubernetes:maximal-permission-policy`. 
```
$ kubectl get clusterrole compute:apiexport:kubernetes:maximal-permission-policy -o yaml | grep 'deployments/scale' -B 3 -A 4
- apiGroups:
  - apps
  resources:
  - deployments/scale
  verbs:
  - get
  - update
  - patch
```

**Comment by MikeSpreitzer** [comment]
I am confused by the first part of the previous comment --- it says "It can be done" and shows a case where the request is NOT accepted.

**Comment by MikeSpreitzer** [comment]
For comparison purposes, I looked at a plain kcp v0.11.0 `root:compute` workspace and found the following in the list of ClusterRoleBindings.

```yaml
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    annotations:
      bootstrap.kcp.io/battery: root-compute-workspace
      bootstrap.kcp.io/create-only: "true"
      internal.kcp.io/replicate: apis.kcp.io
      kcp.io/cluster: 1cp7qpefpbg39z6j
    creationTimestamp: "2023-06-01T20:14:59Z"
    name: compute:authenticated:apiexport:kubernetes:maximal-permission-policy
    resourceVersion: "626"
    uid: 56d9860b-61cd-4703-9f93-a8f4d78f646b
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: compute:apiexport:kubernetes:maximal-permission-policy
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: apis.kcp.io:binding:system:authenticated
```

The original remedy above is not worse than this, so that's good enough for me.

**Comment by MikeSpreitzer** [comment]
I did a little experimentation to see how this might be restricted.  The following ClusterRoleBinding is enough to make the example in https://github.com/kcp-dev/edge-mc/issues/477#issuecomment-1568257287 work.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: compute:authenticated:apiexport:kubernetes:maximal-permission-policy-extended
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: compute:apiexport:kubernetes:maximal-permission-policy-extended
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: apis.kcp.io:binding:kcp-admin
EOF
```

I suspect that adding the following subject would be enough to enable syncers to work, because a syncer uses a ServiceAccount with SyncTarget-dependent name in the namespace named `default`.

```yaml
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: apis.kcp.io:binding:system:serviceaccounts:default
```

**Comment by MikeSpreitzer** [comment]
No, experimentally I see that the namespace of the Syncer's ServiceAccount is dependent on the SyncTarget.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcp-edge-syncer-guilder-2bijre6c
  namespace: kcp-edge-syncer-guilder-2bijre6c
```
