### ISSUE TITLE
bug: upsyncying issue

### ISSUE THREAD

**Issue by tayebehbah** [kcp-dev/edge-mc#625]
### Describe the bug

I'm having trouble with upsyncing objects from edge cluster to mailbox workspace. In edgeplacement, I listed the name of CRs that are needed to be upsynced from edge cluster. I observed that after applying the edgeplacement,  CRs are appropriately created in mailbox workspace; but they are not updated if the CRs  in edge cluster change later.  I think these CRs  are just created in mailbox and will not be updated automatically over time.  

### Steps To Reproduce

My goal is to upsync greencluster objects from edge cluster to mailbox cluster
- Here is the CRD for greencluster:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
 name: greenclusters.stable.example.com
spec:
 group: stable.example.com
 versions:
   - name: v1
     served: true
     storage: true
     schema:
       openAPIV3Schema:
         type: object
         properties:
           spec:
             type: object
             properties:
               cluster:
                 type: string
               cpu:
                 type: integer
               carbon:
                 type: number
               target:
                 type: string
               futureCarbon:
                 type: array
                 items:
                   type: object
                   properties:
                     timeStamp:
                       type: number
                     carbon:
                       type: number     
              
 scope: Cluster
 names:
   plural: greenclusters
   singular: greencluster
   kind: GreenCluster
   shortNames:
   - gc
```
- I updated greencluster object in edge cluster by applying the following yaml file
```
apiVersion: "stable.example.com/v1"
kind: GreenCluster
metadata:
 name: cluster3
spec:
 target: "target"
 cpu: 4040
 carbon: 100
```
 
- In the edge cluster, the value is updated but in the mailbox it is not.
Attached please find the log file for syncer pod; I see an error saying "failed to update"
[pod.log](https://github.com/kcp-dev/edge-mc/files/11767591/pod.log)
 

### Expected Behavior

The generated resources in mailbox workspace must be updated when the corresponding resources in edge cluster are updated.
